### ISSUE TITLE
Configuration tab title looks wrong in Magento admin panel.

### ISSUE THREAD

**Issue by sergey-fedosimov** [YotpoLtd/magento2-module-yotpo-loyalty#29]
Magento EE 2.3.6
Store->Configuration->Yotpo tab
![image](https://user-images.githubusercontent.com/18401050/105461709-2ccc6100-5cc0-11eb-8fc2-c616d257210c.png)

**Comment by copperphilip** [comment]
I am having that same issue with Yotpo Core on Magento CE 2.4.3
