### ISSUE TITLE
Cannot create multiple invoice refunds via Magento API with Yotpo installed

### ISSUE THREAD

**Issue by braders** [YotpoLtd/magento2-module-yotpo-loyalty#32]
I am working on a site utilising Magento, Yotpo and a third-party warehousing system. This warehousing system is pushing refunds to Magento via the Magento Rest API. These refund API calls fail when more than one refund is made against an order's invoice (for example, because the order contains multiple line-items which are refunded separately). I have tracked these failing API calls to an issue in how the Yotpo (loyalty) module handles refunds.

### Environment details

The issue is occurring on Magento cloud (and local environments). 
Magento Commerce ver. 2.4.1 (Enterprise edition)

### Steps to reproduce

- You will need to create API keys for the Magento admin REST api. This can be done in various ways, instructions can be found here: https://devdocs.magento.com/guides/v2.4/rest/tutorials/prerequisite-tasks/create-admin-token.html
-  Create an order with more than one line item, using the front-end checkout flow. 
- Make a post request to https://magento.localhost/rest/V1/invoice/[$invoice_id]/refund with the following payload:

```
{
  "items": [
    {
      "order_item_id": $order_item_id,
      "qty": 1
    }
  ],
  "isOnline": true,
  "notify": true,
  "arguments": {
    "shipping_amount": 0,
    "adjustment_positive": 0,
    "adjustment_negative": 0,
    "extension_attributes": {}
  }
}
```

Replace `$order_item_id` with the ID of the order item you want to refund. I don't think this ID is visible through the admin UI, so I would look this up by connecting directly to the database and looking at the `item_id` column of the `sales_order_item` table. For this first API call I would suggest refunding the first line item from the order created in the previous step.
 
Note also that the endpoint URL contains the invoice ID (not the order ID).

- Re-run the previous API call, with the same invoice ID. However, change the `$order_item_id` to now refer to the second line item of the previously created order.

### Expected result

Two credit memo's (refunds) should be created against the order, and all associated functionality should function correctly (e.g. 2x refund emails should be sent if the API call contained `"notify": true`

### Actual result

The second API call will return a 500 HTTP response. The logs contain the following error:

```
[2021-07-26 14:16:34] report.CRITICAL: Error: Call to a member function isDeleted() on array in /app/vendor/magento/module-sales/Model/Order/Creditmemo.php:312
```

The credit memo is not saved, and the refund not processed. 

### Diagnostics

I believe I have tracked this issue to part of Yotpo's logic, which synchronises refunds to Yotpo (presumably in order to adjust loyalty point balances). The problem occurs in `vendor/yotpo/magento2-module-yotpo-loyalty/Helper/Schema.php` with these lines of code:

```php
$creditMemos = $order->getCreditmemosCollection();
$creditMemoData = [];
try {
    foreach ($creditMemos as $creditMemo) { //go through all the credit memos for the current order.
        $creditMemoItemData = [];
        foreach ($creditMemo->getAllItems() as $creditMemoItem) { //get all credit memo items if needed
            $creditMemoItemData[] = $creditMemoItem->getData();
        }
        $creditMemo->setItems($creditMemoItemData);
        $creditMemoData[] = $creditMemo->getData();
    }
} catch (\Exception $e) {
    //Ignore errors
}
$orderData["refunds"] = $creditMemoData;
```

It appears that the credit memo items are being retrieved as objects with `$creditMemo->getAllItems()`, converted to arrays with `$creditMemoItem->getData()` and then these arrays are set against the $creditMemo object. Later Magento code then tries to retrieve the credit memo items, expects objects but receives arrays, and crashes.

This problem does not occur when creating refunds (credit notes) via the admin UI. This is because Magento uses a different order of execution for API execution vs admin panel execution:

vendor/magento/module-sales/Model/Service/CreditmemoService.php (Admin panel)
```php
$this->creditmemoRepository->save($creditmemo);
$this->getOrderRepository()->save($order);
```

vendor/magento/module-sales/Model/RefundInvoice.php (Rest API)
```php
$order = $this->orderRepository->save($order);
$creditmemo = $this->creditmemoRepository->save($creditmemo);
```

The Yotpo code is expecting the creditmemo to be saved before the order, and failing when this is not the case.

Please let me know if you need any more detail in order to resolve this issue. Many thanks.

**Comment by hadasNagar** [comment]
@braders 

We have a branch with the fix:

The merchant should install the branch version and check if it has fixed the bug

steps:

connect to the machine
go to root folder of the Magento
and run the following commands:
      composer clear-cache

      rm -fR ~/.cache/composer

      composer update

      composer require yotpo/magento2-module-yotpo-loyalty:v1.2.7.x-dev

      php bin/magento maintenance:enable

      php bin/magento setup:upgrade

      php bin/magento setup:di:compile

      php bin/magento setup:static-content:deploy

      php bin/magento maintenance:disable

      php bin/magento cache:flush

**Comment by pniel-cohen** [comment]
Closing old issues. Please re-open if still relevant. Thanks.
