### ISSUE TITLE
Snippet generated wrong URL for the access to the 'rest/V1/swell/session/snippet' endpoint

### ISSUE THREAD

**Issue by bbakalov** [YotpoLtd/magento2-module-yotpo-loyalty#37]
## Environment details
Magento Commerce ver. 2.3.4 (Enterprise edition)

---

I stuck with a problem when this part of the code in the snippet generation file [view/frontend/templates/snippet.phtml](https://github.com/YotpoLtd/magento2-module-yotpo-loyalty/blob/62445f8e07d34a43f24ded6caf035bfdad55c7f8/view/frontend/templates/snippet.phtml)

```
storage.get(
                        url.build('rest/V1/swell/session/snippet')
                    ).done(function (response) {
```

called to the **https://store.com/{cmsPageUrlKey}/rest/V1/swell/session/snippet** instead of **https://store.com/rest/V1/swell/session/snippet**

It happened on the CMS page. 

### Expected result
Call API https://store.com/rest/V1/swell/session/snippet

### Actual result
Call API https://store.com/{cmsPageUrlKey}/rest/V1/swell/session/snippet

---
It happened only on one website. I can't reproduce it on the other test server and my local project.

**Comment by bbakalov** [comment]
I have already prepared a fix for this issue. You can check it in the pull request https://github.com/YotpoLtd/magento2-module-yotpo-loyalty/pull/38

**Comment by namnguyen1998** [comment]
I fixed it by adding "/" before rest and working fine. 
`storage.get(
                        url.build('/rest/V1/swell/session/snippet')
                    ).done(function (response) {`

**Comment by pniel-cohen** [comment]
@namnguyen1998, 
This issue has been fixed almost a year ago.
Please make sure that you are using the latest module version and that you are not overriding `snippet.phtml` on your local theme.
