### ISSUE TITLE
Yotpo Loyalty API crashes Magento Swagger

### ISSUE THREAD

**Issue by ivanweiler** [YotpoLtd/magento2-module-yotpo-loyalty#52]
When Yotpo_Loyalty is installed, it crashes Magentos /swagger API tool.

/rest/all/schema?services=all

```
<response>
<message>
The "\Magento\Framework\Controller\ResultFactory" parameter type is invalid. Verify the parameter and try again.
</message>
...
```

The problem is wrong api return type at:
https://github.com/YotpoLtd/magento2-module-yotpo-loyalty/blob/master/Api/Swell/Index/TestManagementInterface.php#L10

it should probbably be a string.

**Comment by pniel-cohen** [comment]
@ivanweiler 
A fix for that would be included in v1.3.9
Thanks.
